In [1]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [3]:
# 요소별 합; 둘 다 다음의 배열을 만듭니다
# [[ 6.0  8.0]
#  [10.0 12.0]]
print (x + y)
print (np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [4]:
# 행렬곱; 둘 다 결과는 rank 2인 배열
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [5]:
print (np.sum(x))  # 모든 요소를 합한 값을 연산; 출력 "10"
print (np.sum(x, axis=0))  # 각 열에 대한 합을 연산; 출력 "[4 6]"
print (np.sum(x, axis=1))  # 각 행에 대한 합을 연산; 출력 "[3 7]"

10.0
[4. 6.]
[3. 7.]
